// <auto-generated />
namespace BBGFrontEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class DummyData2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DummyData2));
        
        string IMigrationMetadata.Id
        {
            get { return "202001270003108_DummyData2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
